### ISSUE TITLE
Permission issue on raspberry pi

### ISSUE THREAD

**Issue by SailingGreg** [ruuvi-friends/simple-ruuvitag#3]
Installed on raspberry pi Zero W running Buster with Python 3.7.3

Installing collected packages: bleson, simple-ruuvitag
Successfully installed bleson-0.0.10 simple-ruuvitag-0.0.5

The code fragment uses the example in the readme for a couple of tags

```
macs = [insideTag, outsideTag]
ruuvi_client = RuuviTagClient(mac_addresses=macs)
ruuvi_client.start()

last_datas = ruuvi_client.get_current_datas()
print(last_datas)
```

This errors if run without sudo 

```2020-06-27 16:45:20,168   INFO -                bleson.py: 49 -                 __init__(): Observing broadcasts (device 0)
Traceback (most recent call last):
  File "srt.py", line 12, in <module>
    ruuvi_client = RuuviTagClient(mac_addresses=macs)
  File "/usr/local/lib/python3.7/dist-packages/simple_ruuvitag/ruuvi.py", line 46, in __init__
    self.convert_data_and_callback, bt_device=bt_device
  File "/usr/local/lib/python3.7/dist-packages/simple_ruuvitag/adaptors/bleson.py", line 51, in __init__
    adapter = get_provider().get_adapter(int(bt_device))
  File "/usr/local/lib/python3.7/dist-packages/bleson/providers/linux/linux_provider.py", line 11, in get_adapter
    adapter.off()
  File "/usr/local/lib/python3.7/dist-packages/bleson/providers/linux/linux_adapter.py", line 100, in off
    self.send_cmd_value(HCIDEVDOWN, self.device_id)
  File "/usr/local/lib/python3.7/dist-packages/bleson/providers/linux/linux_adapter.py", line 47, in send_cmd_value
    fcntl.ioctl(self._socket.fileno(), cmd, value)
PermissionError: [Errno 1] Operation not permitted
```

**Comment by sergioisidoro** [comment]
@SailingGreg indeed in some OS the access to the bluetooth socket requires sudo. I will update the documentation to reflect these findings, but I'm afraid there's not much we can do on a python level.
